[package]
name = "naive"
version = "0.1.0"
authors = ["Nils André-Chang <nils@nilsand.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
